### ISSUE TITLE
Initial release checklist

### ISSUE THREAD

**Issue by abhinav** [abhinav/git-spice#219]
- [x] Add vanity import path to https://go.abhg.dev
- [x] Publish documentation webiste
- [x] Make GitHub App and OAuth Apps public
- [x] Update homepage for GitHub App/OAuth app to doc website
- [x] Set up goreleaser publishing
    - [x] Publish AUR binary
- [x] Update installation instructions in docs
